import { defineConfig } from 'tsdown'

export default defineConfig({
  entry: { index: 'index-src.ts' },
  outDir: '.',
  outExtensions: () => ({ js: '.js' }),
  format: ['cjs'],
  external: [
    'react',
    'react-dom',
    'react-redux',
    'styled-components',
    'redux-observers',
    'react-fontawesome',
    'views/components/etc/window-env',
    'views/env-parts/i18next',
    'views/utils/selectors',
    'views/utils/tools',
    'views/utils/tools',
    'views/components/etc/overlay',
    'views/create-store',
    'views/utils/ship-img',
    'views/components/etc/avatar',
    'views/components/etc/icon',
    'electron',
    'wanakana',
    'i18next',
    'react-i18next',
  ],
  dts: false,
  clean: false,
  splitting: false,
  sourcemap: true,
  treeshake: true,
  minify: true,
  shims: false,
  target: false,
})
