export interface IShip {
  id: number
  typeId: number
  fleetId: number
  type: string
  name: string
  yomi: string
  sortno: number
  lv: number
  cond: number
  karyoku: number
  houg: number[]
  raisou: number
  raig: number[]
  taiku: number
  tyku: number[]
  soukou: number
  souk: number[]
  lucky: number
  luck: number[]
  kyouka: number[]
  kaihi: number
  taisen: number
  sakuteki: number
  slot: number[]
  exslot: number
  locked: number
  nowhp: number
  maxhp: number
  losshp: number
  repairtime: number
  after: number
  afterLevel: number
  sallyArea: number
  soku: number
  karyokuNow: number
  karyokuMax: number
  raisouNow: number
  raisouMax: number
  taikuNow: number
  taikuMax: number
  soukouNow: number
  soukouMax: number
  luckyNow: number
  luckyMax: number
  isCompleted: boolean
  daihatsu: boolean
  shipId: number
  inDock: boolean
  _karyoku: number
  _taiku: number
  _raisou: number
  _soukou: number
  _lucky: number
  taik: number[]
}
