export default [
  {
    certer: false,
    name: 'id',
    sortable: true,
    title: 'ID',
    width: 50,
  },
  {
    certer: false,
    name: 'name',
    sortable: true,
    title: 'Name',
    width: 220,
  },
  {
    certer: false,
    name: 'type',
    sortable: true,
    title: 'Class',
    width: 90,
  },
  {
    certer: false,
    name: 'soku',
    sortable: true,
    title: 'Speed',
    width: 40,
  },
  {
    certer: true,
    name: 'lv',
    sortable: true,
    title: 'Level',
    width: 40,
  },
  {
    certer: true,
    name: 'cond',
    sortable: true,
    title: 'Cond',
    width: 40,
  },
  {
    certer: true,
    name: 'hp',
    sortable: true,
    title: 'HP',
    width: 40,
  },
  {
    certer: true,
    name: 'karyoku',
    sortable: true,
    title: 'Firepower',
    width: 60,
  },
  {
    certer: true,
    name: 'raisou',
    sortable: true,
    title: 'Torpedo',
    width: 60,
  },
  {
    certer: true,
    name: 'taiku',
    sortable: true,
    title: 'AA',
    width: 60,
  },
  {
    certer: true,
    name: 'soukou',
    sortable: true,
    title: 'Armor',
    width: 60,
  },
  {
    certer: true,
    name: 'lucky',
    sortable: true,
    title: 'Luck',
    width: 60,
  },
  {
    certer: true,
    name: 'kaihi',
    sortable: true,
    title: 'Evasion',
    width: 40,
  },
  {
    certer: true,
    name: 'taisen',
    sortable: true,
    title: 'ASW',
    width: 40,
  },
  {
    certer: true,
    name: 'sakuteki',
    sortable: true,
    title: 'LOS',
    width: 40,
  },
  {
    certer: true,
    name: 'repairtime',
    sortable: true,
    title: 'Repair',
    width: 80,
  },
  {
    certer: false,
    name: 'equipment',
    sortable: false,
    title: 'Equipment',
    width: 180,
  },
  {
    certer: true,
    name: 'lock',
    sortable: false,
    title: 'Lock',
    width: 40,
  },
]
